let boardGames = [
    "Barrel of Monkeys",
    "Donkey Kong",
    "Donkey Kong Country",
    "Diddy Kong Racing",
    "Donkey Kong Barrel Blast",
    "Mario Kart",
    "Gorilla Marketing",
    "GRASS: Bananaham",
    "Donkey Kong Jr.",
    "Banana Blast",
    "Cheeky Monkey",
    "Monkey Madness",
    "Go Ape!",
    "Rumble in the Jungle",
    "Bananagrams",
    "Santorini",
    "Santorini: New York",
    "Dice Throne",
    "Dice Throne Adventures",
    "Steampunk Rally",
    "Steampunk Rally Fusion",
    "Super Motherload",
    "Brass: Birmingham",
    "Brass: Lancashire",
    "SKYRISE",
    "Santorini App",
    "with a coconut",
    "Win, Lose, Or Banana",
    "Tiny Epic Apes",
    "One Night Ultimate Were-ape",
    "Hey, That's My Banana!",
    "Dominant Species",
    "Evolution",
    "Castles of Mad King Kong",
    "Zooloretto",
    "A Few Acres of Jungle",
    "without a full deck",
    "for keeps",
    "with fire",
    "devil's advocate",
    "in traffic",
    "bongos",
    "Fruit Ninja",
    "Super Monkey Ball",
    "Ape Escape",
    "Ape Out",
    "Dissection: Murder By King Kong",
    "Monkey Island",
    "that funky music, white boy",
    "games with your heart",
];

let movies = [
    "King Kong",
    "Congo",
    "Planet of the Apes",
    "Gorillas in the Mist",
    "Kong: Skull Island",
    "Tarzan",
    "The One and Only Ivan",
    "George of the Jungle",
    "Mighty Joe Young",
    "Bride of the Gorilla",
    "Queen Kong",
    "Son of Kong",
    "Magilla Gorilla",
    "Curious George",
    "The Jungle Book",
    "Bananas In Pyjamas",
    "12 Monkeys",
    "Zoboomafoo",
    "Swingers",
    "Space Chimps",
    "Dora The Explorer",
    "Family Guy",
    "my weight",
    "my language",
    "the clock",
    "paint dry",
    "the watchers",
    "a very slow progress bar",
    "Animal Planet",
    "with a stick",
];

let songs = [
    "Monkey, by George Michael",
    "Brass Monkey, by the Beastie Boys",
    "Peter Gabriel - Shock The Monkey",
    "Monkey Wrench, by the Foo Fighters",
    "The Monkees - Daydream Believer",
    "Monkey Man, by the Rolling Stones",
    "Copa Banana, by Barry Bananilow",
    "Gorillaz - Rock The House feat. Del The Funky Homosapien",
    "My Brother The Ape, by They Might Be Giants",
    "Bananarama - Venus",
    "Love Monkey #9, by Bootsauce",
    "Arctic Monkeys - I Bet You Look Good On The Dancefloor",
    "Tarzan Boy, by Baltimora",
    "Jungle Love, by the Steve Miller Band",
    "Welcome To The Jungle, by Guns N' Roses",
    "Jungle Love, by Morris Day and The Time",
    "Bananaphone, by Raffi",
    "Yes, We Have No Bananas, by Louis Prima",
    "Banana Boat Song (Day-O), by Harry Belafonte",
    "Space Monkey, by John Prine",
    "Tweeter and the Monkey Man, by the Traveling Wilburys",
    "99 Red Baboons, by Nena",
    "Code Monkey, by Jonathan Coulton",
    "Everybody's Got Something to Hide Except Me and My Monkey, by The Beatles",
];

module.exports = {
    boardGames: boardGames,
    movies: movies,
    songs: songs
}